version: "3.8"

services:
  # Django App Service
  web:
    build: .
    command: gunicorn bgremove.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000  # Expose port 8000 to other services (not to the host machine)
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=your_secret_key_here
    depends_on:
      - db

  # Database (PostgreSQL, if you're using it)
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bgremove_db
      POSTGRES_USER: bgremove_user
      POSTGRES_PASSWORD: password

  # Nginx Service
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static  # If you're serving static files
    ports:
      - "80:80"  # Exposing port 80 to the host for HTTP traffic
    depends_on:
      - web

volumes:
  postgres_data:
