# Generated by Django 5.1.3 on 2024-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_picture', models.ImageField(upload_to='original_pic')),
                ('bg_removed_picture', models.ImageField(blank=True, null=True, upload_to='bg_removed_pic')),
            ],
        ),
    ]
